/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cme.neptune.qrcodegenerator.gui;

import cme.neptune.qrcodegenerator.utilities.Utilities;
import com.google.zxing.EncodeHintType;
import com.google.zxing.WriterException;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author elie.abdallah
 */
public class GUI extends javax.swing.JFrame {

    Utilities utilities = new Utilities();
    boolean mode = false;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        textToSaveTxtArea.setLineWrap(true);
        textToSaveTxtArea.setWrapStyleWord(true);

        textToSaveTxtArea.setEnabled(false);
        filePath.setEnabled(false);
        
        filePathRadio.setEnabled(false);

        textToSaveTxtArea.setBackground(Color.LIGHT_GRAY);
        filePath.setBackground(Color.LIGHT_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        textRadio = new javax.swing.JRadioButton();
        filePathRadio = new javax.swing.JRadioButton();
        filePath = new javax.swing.JTextField();
        browseBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        widthSpinner = new javax.swing.JSpinner();
        heightSpinner = new javax.swing.JSpinner();
        generateQRCodeBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textToSaveTxtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(680, 500));
        setMinimumSize(new java.awt.Dimension(680, 500));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Configuration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 18))); // NOI18N

        buttonGroup1.add(textRadio);
        textRadio.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        textRadio.setText("TEXT");
        textRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(filePathRadio);
        filePathRadio.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        filePathRadio.setText("FILE");
        filePathRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePathRadioActionPerformed(evt);
            }
        });

        filePath.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N

        browseBtn.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        browseBtn.setText("BROWSE");
        browseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setText("WIDTH");

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setText("HEIGHT");

        widthSpinner.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N

        heightSpinner.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N

        generateQRCodeBtn.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        generateQRCodeBtn.setText("GENERATE");
        generateQRCodeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateQRCodeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(heightSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(widthSpinner)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generateQRCodeBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textRadio)
                        .addGap(18, 18, 18)
                        .addComponent(filePathRadio)
                        .addGap(18, 18, 18)
                        .addComponent(filePath, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(browseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {filePathRadio, textRadio});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {heightSpinner, widthSpinner});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRadio)
                    .addComponent(filePathRadio)
                    .addComponent(filePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(widthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateQRCodeBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(heightSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        textToSaveTxtArea.setColumns(20);
        textToSaveTxtArea.setRows(5);
        jScrollPane1.setViewportView(textToSaveTxtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRadioActionPerformed
        if (textRadio.isSelected()) {
            textToSaveTxtArea.setEnabled(true);
            textToSaveTxtArea.setBackground(Color.WHITE);
            filePath.setEnabled(false);
            filePath.setBackground(Color.LIGHT_GRAY);
            mode = false;
        }
    }//GEN-LAST:event_textRadioActionPerformed

    private void filePathRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePathRadioActionPerformed
        if (filePathRadio.isSelected()) {
            filePath.setEnabled(true);
            filePath.setBackground(Color.WHITE);
            textToSaveTxtArea.setEnabled(false);
            textToSaveTxtArea.setBackground(Color.LIGHT_GRAY);
            mode = true;
        }
    }//GEN-LAST:event_filePathRadioActionPerformed

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("All Files (*.*)", "*.*");
        fileChooser.addChoosableFileFilter(filter);
        int clicked = fileChooser.showOpenDialog(null);
        if (clicked == JFileChooser.APPROVE_OPTION) {
            filePath.setText(fileChooser.getSelectedFile().getAbsolutePath());
        } else {
            filePath.setText("");
        }
    }//GEN-LAST:event_browseBtnActionPerformed

    private void generateQRCodeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateQRCodeBtnActionPerformed
        try {
            String str = "THE HABIT OF PERSISTENCE IS THE HABIT OF VICTORY.";
            String path = "Quote.png";
            String charset = "UTF-8";
            Map<EncodeHintType, ErrorCorrectionLevel> hashMap = new HashMap<>();
            hashMap.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.L);
            int height = Integer.parseInt(heightSpinner.getValue().toString());
            int width = Integer.parseInt(widthSpinner.getValue().toString());
            utilities.generateQRcode(mode, textToSaveTxtArea.getText().trim(), new File(filePath.getText().trim()), charset, hashMap, height, width, path);
        } catch (IOException | WriterException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_generateQRCodeBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField filePath;
    private javax.swing.JRadioButton filePathRadio;
    private javax.swing.JButton generateQRCodeBtn;
    private javax.swing.JSpinner heightSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton textRadio;
    private javax.swing.JTextArea textToSaveTxtArea;
    private javax.swing.JSpinner widthSpinner;
    // End of variables declaration//GEN-END:variables
}
